/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/astronave.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle002_Circle001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Circle002_Circle001_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Circle002_Circle001_3.geometry} material={materials.pannelli} />
      </group>
    </group>
  )
}

useGLTF.preload('/astronave.glb')
