/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { OrbitControls } from "@react-three/drei";
 

export default function Model({ position, ...props }) {

  // const [mouseX, setMouseX] = useState(0)


  // document.addEventListener('mousemove', function(e){
  //   let scale = -0.01;
  //   setMouseX(e.movementX * scale);
  // })


  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/forWorld.glb')
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    actions['KeyAction.001'].play();
    actions['Action.002'].play();
    actions['Action.003'].play();
    actions['Action.004'].play();
    actions['Action.005'].play();
    actions['Action.006'].play();
    actions['Action.007'].play();
  })


  return (
    <>
    {/* <OrbitControls enablePan={false} enableZoom={false} enabledRotate={true} maxAzimuthAngle={Math.PI/2} minAzimuthAngle={Math.PI} maxPolarAngle={Math.PI/2} minPolarAngle={Math.PI/2}/> */}
    <group ref={group} {...props} dispose={null} position={position}>
      <group name="Scene">
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.010']} scale={6.13}>
          <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials['Material.008']} position={[1, 0, 0]} scale={0.06} />
        </mesh>
        <mesh name="Circle643" geometry={nodes.Circle643.geometry} material={materials['Material.010']} scale={4.79} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.012']} rotation={[Math.PI, -0.13, Math.PI]} scale={0.97} />
        <mesh name="TERRE1" geometry={nodes.TERRE1.geometry} material={materials.Material} scale={3.27} />
        <mesh name="Circle455" geometry={nodes.Circle455.geometry} material={materials.Material} morphTargetDictionary={nodes.Circle455.morphTargetDictionary} morphTargetInfluences={nodes.Circle455.morphTargetInfluences} scale={0.18} />
      </group>
    </group>
    </>
  )
}

useGLTF.preload('/forWorld.glb')
