/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/futura.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Armature.001|Armature.001|ArmatureAction.001'].play();
  })

  const pivot = useRef()
  useFrame(() => (group.current.rotation.y += 0.01));



  return (
    <group ref={pivot}>

    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" position={[24.99, -59.16, 18.2]}>
          <primitive object={nodes.Torso} />
          <primitive object={nodes.RightEyeLid} />
          <primitive object={nodes.LeftEyeLid} />
          <primitive object={nodes.RightShoulder} />
          <primitive object={nodes.LeftShoulder} />
          <primitive object={nodes.RightEye} />
          <primitive object={nodes.LeftEye} />
          <primitive object={nodes.HairStrand} />
          <primitive object={nodes.Earring} />
          <group name="Empty004" position={[-37.66, 135.07, -26.97]} />
          <group name="Empty005" position={[-37.66, 135.07, -26.97]} />
          <group name="Icosphere_Curve" position={[-24.99, 59.86, -18.2]} />
          <group name="Icosphere_Curve001" position={[-24.99, 59.86, -18.2]} />
          <group name="Rope_Twist" position={[-4.89, 95.51, 0.09]} />
          <skinnedMesh name="Capacitor" geometry={nodes.Capacitor.geometry} material={materials.Lips} skeleton={nodes.Capacitor.skeleton} />
          <skinnedMesh name="Capacitor001" geometry={nodes.Capacitor001.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor001.skeleton} />
          <skinnedMesh name="Capacitor002" geometry={nodes.Capacitor002.geometry} material={materials.Lips} skeleton={nodes.Capacitor002.skeleton} />
          <skinnedMesh name="Capacitor003" geometry={nodes.Capacitor003.geometry} material={materials.Lips} skeleton={nodes.Capacitor003.skeleton} />
          <skinnedMesh name="Capacitor004" geometry={nodes.Capacitor004.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor004.skeleton} />
          <skinnedMesh name="Capacitor005" geometry={nodes.Capacitor005.geometry} material={materials.Lips} skeleton={nodes.Capacitor005.skeleton} />
          <skinnedMesh name="Capacitor006" geometry={nodes.Capacitor006.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor006.skeleton} />
          <skinnedMesh name="Capacitor007" geometry={nodes.Capacitor007.geometry} material={materials.Lips} skeleton={nodes.Capacitor007.skeleton} />
          <skinnedMesh name="Capacitor008" geometry={nodes.Capacitor008.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor008.skeleton} />
          <skinnedMesh name="Capacitor009" geometry={nodes.Capacitor009.geometry} material={materials.Lips} skeleton={nodes.Capacitor009.skeleton} />
          <skinnedMesh name="Capacitor010" geometry={nodes.Capacitor010.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor010.skeleton} />
          <skinnedMesh name="Capacitor011" geometry={nodes.Capacitor011.geometry} material={materials.Lips} skeleton={nodes.Capacitor011.skeleton} />
          <skinnedMesh name="Capacitor012" geometry={nodes.Capacitor012.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor012.skeleton} />
          <skinnedMesh name="Capacitor013" geometry={nodes.Capacitor013.geometry} material={materials.Lips} skeleton={nodes.Capacitor013.skeleton} />
          <skinnedMesh name="Capacitor014" geometry={nodes.Capacitor014.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor014.skeleton} />
          <skinnedMesh name="Capacitor015" geometry={nodes.Capacitor015.geometry} material={materials.Lips} skeleton={nodes.Capacitor015.skeleton} />
          <skinnedMesh name="Capacitor016" geometry={nodes.Capacitor016.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor016.skeleton} />
          <skinnedMesh name="Capacitor017" geometry={nodes.Capacitor017.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor017.skeleton} />
          <skinnedMesh name="Capacitor018" geometry={nodes.Capacitor018.geometry} material={materials.Lips} skeleton={nodes.Capacitor018.skeleton} />
          <skinnedMesh name="Capacitor019" geometry={nodes.Capacitor019.geometry} material={materials.BlueCables} skeleton={nodes.Capacitor019.skeleton} />
          <skinnedMesh name="Chip" geometry={nodes.Chip.geometry} material={materials.Skin} skeleton={nodes.Chip.skeleton} />
          <skinnedMesh name="Chip001" geometry={nodes.Chip001.geometry} material={materials.BlackRubber} skeleton={nodes.Chip001.skeleton} />
          <skinnedMesh name="Chip002" geometry={nodes.Chip002.geometry} material={materials.Skin} skeleton={nodes.Chip002.skeleton} />
          <skinnedMesh name="Chip003" geometry={nodes.Chip003.geometry} material={materials.BlackRubber} skeleton={nodes.Chip003.skeleton} />
          <skinnedMesh name="Chip004" geometry={nodes.Chip004.geometry} material={materials.Skin} skeleton={nodes.Chip004.skeleton} />
          <skinnedMesh name="Chip005" geometry={nodes.Chip005.geometry} material={materials.Skin} skeleton={nodes.Chip005.skeleton} />
          <skinnedMesh name="Chip006" geometry={nodes.Chip006.geometry} material={materials.BlackRubber} skeleton={nodes.Chip006.skeleton} />
          <skinnedMesh name="Chip007" geometry={nodes.Chip007.geometry} material={materials.BlackRubber} skeleton={nodes.Chip007.skeleton} />
          <skinnedMesh name="Chip008" geometry={nodes.Chip008.geometry} material={materials.Skin} skeleton={nodes.Chip008.skeleton} />
          <skinnedMesh name="Chip009" geometry={nodes.Chip009.geometry} material={materials.BlackRubber} skeleton={nodes.Chip009.skeleton} />
          <skinnedMesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.BlackRubber} skeleton={nodes.Cube001.skeleton} />
          <skinnedMesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Metal} skeleton={nodes.Cube002.skeleton} />
          <skinnedMesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials.BlackRubber} skeleton={nodes.Cube003.skeleton} />
          <skinnedMesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.Metal} skeleton={nodes.Cube004.skeleton} />
          <skinnedMesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.BlackRubber} skeleton={nodes.Cube006.skeleton} />
          <skinnedMesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Metal} skeleton={nodes.Cube007.skeleton} />
          <skinnedMesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Metal} skeleton={nodes.Cube012.skeleton} />
          <skinnedMesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.BlackRubber} skeleton={nodes.Cube013.skeleton} />
          <skinnedMesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Metal} skeleton={nodes.Cube014.skeleton} />
          <group name="Cube081">
            <skinnedMesh name="Cube081_1" geometry={nodes.Cube081_1.geometry} material={materials.BlackRubber} skeleton={nodes.Cube081_1.skeleton} />
            <skinnedMesh name="Cube081_2" geometry={nodes.Cube081_2.geometry} material={materials.Emission} skeleton={nodes.Cube081_2.skeleton} />
          </group>
          <skinnedMesh name="Cylinder007" geometry={nodes.Cylinder007.geometry} material={materials.BlackRubber} skeleton={nodes.Cylinder007.skeleton} />
          <skinnedMesh name="Cylinder_Curve" geometry={nodes.Cylinder_Curve.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve.skeleton} />
          <skinnedMesh name="Cylinder_Curve001" geometry={nodes.Cylinder_Curve001.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve001.skeleton} />
          <skinnedMesh name="Cylinder_Curve002" geometry={nodes.Cylinder_Curve002.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve002.skeleton} />
          <skinnedMesh name="Cylinder_Curve003" geometry={nodes.Cylinder_Curve003.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve003.skeleton} />
          <skinnedMesh name="Cylinder_Curve004" geometry={nodes.Cylinder_Curve004.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve004.skeleton} />
          <skinnedMesh name="Cylinder_Curve005" geometry={nodes.Cylinder_Curve005.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve005.skeleton} />
          <skinnedMesh name="Cylinder_Curve006" geometry={nodes.Cylinder_Curve006.geometry} material={materials.BeigeCables} skeleton={nodes.Cylinder_Curve006.skeleton} />
          <skinnedMesh name="Cylinder_Curve007" geometry={nodes.Cylinder_Curve007.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve007.skeleton} />
          <skinnedMesh name="Cylinder_Curve008" geometry={nodes.Cylinder_Curve008.geometry} material={materials.BeigeCables} skeleton={nodes.Cylinder_Curve008.skeleton} />
          <skinnedMesh name="Cylinder_Curve009" geometry={nodes.Cylinder_Curve009.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve009.skeleton} />
          <skinnedMesh name="Cylinder_Curve010" geometry={nodes.Cylinder_Curve010.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve010.skeleton} />
          <skinnedMesh name="Cylinder_Curve011" geometry={nodes.Cylinder_Curve011.geometry} material={materials.BeigeCables} skeleton={nodes.Cylinder_Curve011.skeleton} />
          <skinnedMesh name="Cylinder_Curve012" geometry={nodes.Cylinder_Curve012.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve012.skeleton} />
          <skinnedMesh name="Cylinder_Curve013" geometry={nodes.Cylinder_Curve013.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve013.skeleton} />
          <skinnedMesh name="Cylinder_Curve014" geometry={nodes.Cylinder_Curve014.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve014.skeleton} />
          <skinnedMesh name="Cylinder_Curve015" geometry={nodes.Cylinder_Curve015.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve015.skeleton} />
          <group name="Cylinder_Curve016">
            <skinnedMesh name="Cylinder_Curve016_1" geometry={nodes.Cylinder_Curve016_1.geometry} material={materials.BlackRubber} skeleton={nodes.Cylinder_Curve016_1.skeleton} />
            <skinnedMesh name="Cylinder_Curve016_2" geometry={nodes.Cylinder_Curve016_2.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve016_2.skeleton} />
            <skinnedMesh name="Cylinder_Curve016_3" geometry={nodes.Cylinder_Curve016_3.geometry} material={materials.Metal} skeleton={nodes.Cylinder_Curve016_3.skeleton} />
          </group>
          <group name="Cylinder_Curve017">
            <skinnedMesh name="Cylinder_Curve017_1" geometry={nodes.Cylinder_Curve017_1.geometry} material={materials.BlackRubber} skeleton={nodes.Cylinder_Curve017_1.skeleton} />
            <skinnedMesh name="Cylinder_Curve017_2" geometry={nodes.Cylinder_Curve017_2.geometry} material={materials.BlueCables} skeleton={nodes.Cylinder_Curve017_2.skeleton} />
            <skinnedMesh name="Cylinder_Curve017_3" geometry={nodes.Cylinder_Curve017_3.geometry} material={materials.Metal} skeleton={nodes.Cylinder_Curve017_3.skeleton} />
          </group>
          <group name="Ear">
            <skinnedMesh name="Ear_1" geometry={nodes.Ear_1.geometry} material={materials.Skin} skeleton={nodes.Ear_1.skeleton} />
            <skinnedMesh name="Ear_2" geometry={nodes.Ear_2.geometry} material={materials.BlackRubber} skeleton={nodes.Ear_2.skeleton} />
          </group>
          <group name="Ear003">
            <skinnedMesh name="Ear003_1" geometry={nodes.Ear003_1.geometry} material={materials.Skin} skeleton={nodes.Ear003_1.skeleton} />
            <skinnedMesh name="Ear003_2" geometry={nodes.Ear003_2.geometry} material={materials.BlackRubber} skeleton={nodes.Ear003_2.skeleton} />
          </group>
          <skinnedMesh name="EyeHiddenPlane" geometry={nodes.EyeHiddenPlane.geometry} material={materials.BlackRubber} skeleton={nodes.EyeHiddenPlane.skeleton} />
          <skinnedMesh name="EyeLashes" geometry={nodes.EyeLashes.geometry} material={materials.BlackRubber} skeleton={nodes.EyeLashes.skeleton} />
          <skinnedMesh name="EyeLashes001" geometry={nodes.EyeLashes001.geometry} material={materials.BlackRubber} skeleton={nodes.EyeLashes001.skeleton} />
          <group name="EyeLidPlate001">
            <skinnedMesh name="EyeLidPlate001_1" geometry={nodes.EyeLidPlate001_1.geometry} material={materials.Skin} skeleton={nodes.EyeLidPlate001_1.skeleton} />
            <skinnedMesh name="EyeLidPlate001_2" geometry={nodes.EyeLidPlate001_2.geometry} material={materials.BlackRubber} skeleton={nodes.EyeLidPlate001_2.skeleton} />
          </group>
          <group name="EyeLidPlate003">
            <skinnedMesh name="EyeLidPlate003_1" geometry={nodes.EyeLidPlate003_1.geometry} material={materials.Skin} skeleton={nodes.EyeLidPlate003_1.skeleton} />
            <skinnedMesh name="EyeLidPlate003_2" geometry={nodes.EyeLidPlate003_2.geometry} material={materials.BlackRubber} skeleton={nodes.EyeLidPlate003_2.skeleton} />
          </group>
          <skinnedMesh name="FacePlate" geometry={nodes.FacePlate.geometry} material={materials.Skin} skeleton={nodes.FacePlate.skeleton} />
          <skinnedMesh name="FacePlate001" geometry={nodes.FacePlate001.geometry} material={materials.Skin} skeleton={nodes.FacePlate001.skeleton} />
          <skinnedMesh name="FacePlate002" geometry={nodes.FacePlate002.geometry} material={materials.Skin} skeleton={nodes.FacePlate002.skeleton} />
          <skinnedMesh name="FacePlate003" geometry={nodes.FacePlate003.geometry} material={materials.Skin} skeleton={nodes.FacePlate003.skeleton} />
          <skinnedMesh name="FacePlate004" geometry={nodes.FacePlate004.geometry} material={materials.Skin} skeleton={nodes.FacePlate004.skeleton} />
          <skinnedMesh name="FacePlate005" geometry={nodes.FacePlate005.geometry} material={materials.Skin} skeleton={nodes.FacePlate005.skeleton} />
          <skinnedMesh name="FacePlate006" geometry={nodes.FacePlate006.geometry} material={materials.Skin} skeleton={nodes.FacePlate006.skeleton} />
          <skinnedMesh name="FacePlate007" geometry={nodes.FacePlate007.geometry} material={materials.Skin} skeleton={nodes.FacePlate007.skeleton} />
          <skinnedMesh name="FacePlate008" geometry={nodes.FacePlate008.geometry} material={materials.Skin} skeleton={nodes.FacePlate008.skeleton} />
          <skinnedMesh name="FacePlate009" geometry={nodes.FacePlate009.geometry} material={materials.Skin} skeleton={nodes.FacePlate009.skeleton} />
          <skinnedMesh name="FacePlate010" geometry={nodes.FacePlate010.geometry} material={materials.Skin} skeleton={nodes.FacePlate010.skeleton} />
          <skinnedMesh name="FacePlate011" geometry={nodes.FacePlate011.geometry} material={materials.Skin} skeleton={nodes.FacePlate011.skeleton} />
          <skinnedMesh name="FacePlate012" geometry={nodes.FacePlate012.geometry} material={materials.Skin} skeleton={nodes.FacePlate012.skeleton} />
          <skinnedMesh name="FacePlate013" geometry={nodes.FacePlate013.geometry} material={materials.Skin} skeleton={nodes.FacePlate013.skeleton} />
          <skinnedMesh name="FacePlate014" geometry={nodes.FacePlate014.geometry} material={materials.Skin} skeleton={nodes.FacePlate014.skeleton} />
          <skinnedMesh name="FacePlate015" geometry={nodes.FacePlate015.geometry} material={materials.Skin} skeleton={nodes.FacePlate015.skeleton} />
          <skinnedMesh name="FacePlate016" geometry={nodes.FacePlate016.geometry} material={materials.Skin} skeleton={nodes.FacePlate016.skeleton} />
          <skinnedMesh name="FacePlate017" geometry={nodes.FacePlate017.geometry} material={materials.Skin} skeleton={nodes.FacePlate017.skeleton} />
          <skinnedMesh name="FacePlate018" geometry={nodes.FacePlate018.geometry} material={materials.Skin} skeleton={nodes.FacePlate018.skeleton} />
          <skinnedMesh name="FacePlate019" geometry={nodes.FacePlate019.geometry} material={materials.Skin} skeleton={nodes.FacePlate019.skeleton} />
          <skinnedMesh name="FacePlate020" geometry={nodes.FacePlate020.geometry} material={materials.Skin} skeleton={nodes.FacePlate020.skeleton} />
          <skinnedMesh name="FacePlate021" geometry={nodes.FacePlate021.geometry} material={materials.Skin} skeleton={nodes.FacePlate021.skeleton} />
          <skinnedMesh name="FacePlate022" geometry={nodes.FacePlate022.geometry} material={materials.Skin} skeleton={nodes.FacePlate022.skeleton} />
          <skinnedMesh name="FacePlate023" geometry={nodes.FacePlate023.geometry} material={materials.Skin} skeleton={nodes.FacePlate023.skeleton} />
          <skinnedMesh name="FacePlate024" geometry={nodes.FacePlate024.geometry} material={materials.BlackRubber} skeleton={nodes.FacePlate024.skeleton} />
          <skinnedMesh name="FacePlatePCB" geometry={nodes.FacePlatePCB.geometry} material={materials.BeigeCables} skeleton={nodes.FacePlatePCB.skeleton} />
          <skinnedMesh name="FacePlatePCB001" geometry={nodes.FacePlatePCB001.geometry} material={materials.BlueCables} skeleton={nodes.FacePlatePCB001.skeleton} />
          <skinnedMesh name="FacePlatePCB002" geometry={nodes.FacePlatePCB002.geometry} material={materials.PCB} skeleton={nodes.FacePlatePCB002.skeleton} />
          <group name="GP_Layer001">
            <skinnedMesh name="GP_Layer001_1" geometry={nodes.GP_Layer001_1.geometry} material={materials.BlackRubber} skeleton={nodes.GP_Layer001_1.skeleton} />
            <skinnedMesh name="GP_Layer001_2" geometry={nodes.GP_Layer001_2.geometry} material={materials.Metal} skeleton={nodes.GP_Layer001_2.skeleton} />
            <skinnedMesh name="GP_Layer001_3" geometry={nodes.GP_Layer001_3.geometry} material={materials.BeigeCables} skeleton={nodes.GP_Layer001_3.skeleton} />
          </group>
          <group name="GP_Layer005">
            <skinnedMesh name="GP_Layer005_1" geometry={nodes.GP_Layer005_1.geometry} material={materials.BlackRubber} skeleton={nodes.GP_Layer005_1.skeleton} />
            <skinnedMesh name="GP_Layer005_2" geometry={nodes.GP_Layer005_2.geometry} material={materials.Metal} skeleton={nodes.GP_Layer005_2.skeleton} />
            <skinnedMesh name="GP_Layer005_3" geometry={nodes.GP_Layer005_3.geometry} material={materials.BeigeCables} skeleton={nodes.GP_Layer005_3.skeleton} />
          </group>
          <group name="GP_Layer008">
            <skinnedMesh name="GP_Layer008_1" geometry={nodes.GP_Layer008_1.geometry} material={materials.BlackRubber} skeleton={nodes.GP_Layer008_1.skeleton} />
            <skinnedMesh name="GP_Layer008_2" geometry={nodes.GP_Layer008_2.geometry} material={materials.Metal} skeleton={nodes.GP_Layer008_2.skeleton} />
            <skinnedMesh name="GP_Layer008_3" geometry={nodes.GP_Layer008_3.geometry} material={materials.BeigeCables} skeleton={nodes.GP_Layer008_3.skeleton} />
          </group>
          <group name="GP_Layer011">
            <skinnedMesh name="GP_Layer011_1" geometry={nodes.GP_Layer011_1.geometry} material={materials.BlackRubber} skeleton={nodes.GP_Layer011_1.skeleton} />
            <skinnedMesh name="GP_Layer011_2" geometry={nodes.GP_Layer011_2.geometry} material={materials.Metal} skeleton={nodes.GP_Layer011_2.skeleton} />
            <skinnedMesh name="GP_Layer011_3" geometry={nodes.GP_Layer011_3.geometry} material={materials.BeigeCables} skeleton={nodes.GP_Layer011_3.skeleton} />
          </group>
          <skinnedMesh name="GP_Layer013" geometry={nodes.GP_Layer013.geometry} material={materials.BlueCables} skeleton={nodes.GP_Layer013.skeleton} />
          <skinnedMesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials.BlackRubber} skeleton={nodes.Icosphere002.skeleton} />
          <group name="Icosphere003">
            <skinnedMesh name="Icosphere003_1" geometry={nodes.Icosphere003_1.geometry} material={materials.Skin} skeleton={nodes.Icosphere003_1.skeleton} />
            <skinnedMesh name="Icosphere003_2" geometry={nodes.Icosphere003_2.geometry} material={materials.Metal} skeleton={nodes.Icosphere003_2.skeleton} />
            <skinnedMesh name="Icosphere003_3" geometry={nodes.Icosphere003_3.geometry} material={materials.Pearl} skeleton={nodes.Icosphere003_3.skeleton} />
          </group>
          <skinnedMesh name="Icosphere005" geometry={nodes.Icosphere005.geometry} material={materials.Metal} skeleton={nodes.Icosphere005.skeleton} />
          <group name="Icosphere007">
            <skinnedMesh name="Icosphere007_1" geometry={nodes.Icosphere007_1.geometry} material={materials.Skin} skeleton={nodes.Icosphere007_1.skeleton} />
            <skinnedMesh name="Icosphere007_2" geometry={nodes.Icosphere007_2.geometry} material={materials.Emission} skeleton={nodes.Icosphere007_2.skeleton} />
          </group>
          <skinnedMesh name="Icosphere008" geometry={nodes.Icosphere008.geometry} material={materials.Metal} skeleton={nodes.Icosphere008.skeleton} />
          <group name="Icosphere009">
            <skinnedMesh name="Icosphere009_1" geometry={nodes.Icosphere009_1.geometry} material={materials.BlackRubber} skeleton={nodes.Icosphere009_1.skeleton} />
            <skinnedMesh name="Icosphere009_2" geometry={nodes.Icosphere009_2.geometry} material={materials.BeigeCables} skeleton={nodes.Icosphere009_2.skeleton} />
          </group>
          <group name="Icosphere010">
            <skinnedMesh name="Icosphere010_1" geometry={nodes.Icosphere010_1.geometry} material={materials.BlackRubber} skeleton={nodes.Icosphere010_1.skeleton} />
            <skinnedMesh name="Icosphere010_2" geometry={nodes.Icosphere010_2.geometry} material={materials.BlueCables} skeleton={nodes.Icosphere010_2.skeleton} />
          </group>
          <group name="Icosphere011">
            <skinnedMesh name="Icosphere011_1" geometry={nodes.Icosphere011_1.geometry} material={materials.Skin} skeleton={nodes.Icosphere011_1.skeleton} />
            <skinnedMesh name="Icosphere011_2" geometry={nodes.Icosphere011_2.geometry} material={materials.Emission} skeleton={nodes.Icosphere011_2.skeleton} />
          </group>
          <group name="Icosphere013">
            <skinnedMesh name="Icosphere013_1" geometry={nodes.Icosphere013_1.geometry} material={materials.BlackRubber} skeleton={nodes.Icosphere013_1.skeleton} />
            <skinnedMesh name="Icosphere013_2" geometry={nodes.Icosphere013_2.geometry} material={materials.Emission} skeleton={nodes.Icosphere013_2.skeleton} />
          </group>
          <group name="LeftEye_1">
            <skinnedMesh name="LeftEye_2" geometry={nodes.LeftEye_2.geometry} material={materials.Skin} skeleton={nodes.LeftEye_2.skeleton} />
            <skinnedMesh name="LeftEye_3" geometry={nodes.LeftEye_3.geometry} material={materials.BlackRubber} skeleton={nodes.LeftEye_3.skeleton} />
            <skinnedMesh name="LeftEye_4" geometry={nodes.LeftEye_4.geometry} material={materials.Refraction} skeleton={nodes.LeftEye_4.skeleton} />
            <skinnedMesh name="LeftEye_5" geometry={nodes.LeftEye_5.geometry} material={materials.Emission} skeleton={nodes.LeftEye_5.skeleton} />
          </group>
          <skinnedMesh name="LowerFace" geometry={nodes.LowerFace.geometry} material={materials.BlackRubber} skeleton={nodes.LowerFace.skeleton} />
          <group name="Mouth001">
            <skinnedMesh name="Mouth001_1" geometry={nodes.Mouth001_1.geometry} material={materials.Skin} skeleton={nodes.Mouth001_1.skeleton} />
            <skinnedMesh name="Mouth001_2" geometry={nodes.Mouth001_2.geometry} material={materials.BlackRubber} skeleton={nodes.Mouth001_2.skeleton} />
            <skinnedMesh name="Mouth001_3" geometry={nodes.Mouth001_3.geometry} material={materials.Lips} skeleton={nodes.Mouth001_3.skeleton} />
          </group>
          <skinnedMesh name="Pins" geometry={nodes.Pins.geometry} material={materials.Metal} skeleton={nodes.Pins.skeleton} />
          <skinnedMesh name="Pins001" geometry={nodes.Pins001.geometry} material={materials.Metal} skeleton={nodes.Pins001.skeleton} />
          <skinnedMesh name="Pins002" geometry={nodes.Pins002.geometry} material={materials.Metal} skeleton={nodes.Pins002.skeleton} />
          <skinnedMesh name="Pins003" geometry={nodes.Pins003.geometry} material={materials.Metal} skeleton={nodes.Pins003.skeleton} />
          <skinnedMesh name="Pins004" geometry={nodes.Pins004.geometry} material={materials.Metal} skeleton={nodes.Pins004.skeleton} />
          <skinnedMesh name="Pins005" geometry={nodes.Pins005.geometry} material={materials.Metal} skeleton={nodes.Pins005.skeleton} />
          <skinnedMesh name="Pins006" geometry={nodes.Pins006.geometry} material={materials.Metal} skeleton={nodes.Pins006.skeleton} />
          <skinnedMesh name="Pins007" geometry={nodes.Pins007.geometry} material={materials.Metal} skeleton={nodes.Pins007.skeleton} />
          <skinnedMesh name="Pins008" geometry={nodes.Pins008.geometry} material={materials.Metal} skeleton={nodes.Pins008.skeleton} />
          <skinnedMesh name="Pins009" geometry={nodes.Pins009.geometry} material={materials.Metal} skeleton={nodes.Pins009.skeleton} />
          <skinnedMesh name="Pins010" geometry={nodes.Pins010.geometry} material={materials.Metal} skeleton={nodes.Pins010.skeleton} />
          <skinnedMesh name="Pins011" geometry={nodes.Pins011.geometry} material={materials.Metal} skeleton={nodes.Pins011.skeleton} />
          <skinnedMesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Skin} skeleton={nodes.Plane.skeleton} />
          <skinnedMesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.BlackRubber} skeleton={nodes.Plane001.skeleton} />
          <skinnedMesh name="Plane001_Plate" geometry={nodes.Plane001_Plate.geometry} material={materials.BeigeCables} skeleton={nodes.Plane001_Plate.skeleton} />
          <skinnedMesh name="Plane001_Plate001" geometry={nodes.Plane001_Plate001.geometry} material={materials.BeigeCables} skeleton={nodes.Plane001_Plate001.skeleton} />
          <skinnedMesh name="Plane002_Curve001" geometry={nodes.Plane002_Curve001.geometry} material={materials.Emission} skeleton={nodes.Plane002_Curve001.skeleton} />
          <skinnedMesh name="Plane002_Plate" geometry={nodes.Plane002_Plate.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate.skeleton} />
          <skinnedMesh name="Plane002_Plate001" geometry={nodes.Plane002_Plate001.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate001.skeleton} />
          <skinnedMesh name="Plane002_Plate002" geometry={nodes.Plane002_Plate002.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate002.skeleton} />
          <skinnedMesh name="Plane002_Plate003" geometry={nodes.Plane002_Plate003.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate003.skeleton} />
          <skinnedMesh name="Plane002_Plate004" geometry={nodes.Plane002_Plate004.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate004.skeleton} />
          <skinnedMesh name="Plane002_Plate005" geometry={nodes.Plane002_Plate005.geometry} material={materials.BeigeCables} skeleton={nodes.Plane002_Plate005.skeleton} />
          <skinnedMesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.Skin} skeleton={nodes.Plane006.skeleton} />
          <skinnedMesh name="Resistor" geometry={nodes.Resistor.geometry} material={materials.BlackRubber} skeleton={nodes.Resistor.skeleton} />
          <skinnedMesh name="Resistor001" geometry={nodes.Resistor001.geometry} material={materials.BlackRubber} skeleton={nodes.Resistor001.skeleton} />
          <skinnedMesh name="Resistor002" geometry={nodes.Resistor002.geometry} material={materials.Metal} skeleton={nodes.Resistor002.skeleton} />
          <skinnedMesh name="Resistor003" geometry={nodes.Resistor003.geometry} material={materials.Metal} skeleton={nodes.Resistor003.skeleton} />
          <skinnedMesh name="Resistor004" geometry={nodes.Resistor004.geometry} material={materials.BlackRubber} skeleton={nodes.Resistor004.skeleton} />
          <skinnedMesh name="Resistor005" geometry={nodes.Resistor005.geometry} material={materials.Metal} skeleton={nodes.Resistor005.skeleton} />
          <skinnedMesh name="Resistor006" geometry={nodes.Resistor006.geometry} material={materials.BlackRubber} skeleton={nodes.Resistor006.skeleton} />
          <skinnedMesh name="Resistor007" geometry={nodes.Resistor007.geometry} material={materials.Metal} skeleton={nodes.Resistor007.skeleton} />
          <skinnedMesh name="Resistor008" geometry={nodes.Resistor008.geometry} material={materials.BlackRubber} skeleton={nodes.Resistor008.skeleton} />
          <skinnedMesh name="Resistor009" geometry={nodes.Resistor009.geometry} material={materials.Metal} skeleton={nodes.Resistor009.skeleton} />
          <group name="RightEye001">
            <skinnedMesh name="RightEye001_1" geometry={nodes.RightEye001_1.geometry} material={materials.Skin} skeleton={nodes.RightEye001_1.skeleton} />
            <skinnedMesh name="RightEye001_2" geometry={nodes.RightEye001_2.geometry} material={materials.BlackRubber} skeleton={nodes.RightEye001_2.skeleton} />
            <skinnedMesh name="RightEye001_3" geometry={nodes.RightEye001_3.geometry} material={materials.Refraction} skeleton={nodes.RightEye001_3.skeleton} />
            <skinnedMesh name="RightEye001_4" geometry={nodes.RightEye001_4.geometry} material={materials.Emission} skeleton={nodes.RightEye001_4.skeleton} />
          </group>
          <skinnedMesh name="Rope" geometry={nodes.Rope.geometry} material={materials.Skin} skeleton={nodes.Rope.skeleton} />
          <skinnedMesh name="SmallCables" geometry={nodes.SmallCables.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables.skeleton} />
          <skinnedMesh name="SmallCables001" geometry={nodes.SmallCables001.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables001.skeleton} />
          <skinnedMesh name="SmallCables002" geometry={nodes.SmallCables002.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables002.skeleton} />
          <skinnedMesh name="SmallCables003" geometry={nodes.SmallCables003.geometry} material={materials.Metal} skeleton={nodes.SmallCables003.skeleton} />
          <skinnedMesh name="SmallCables004" geometry={nodes.SmallCables004.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables004.skeleton} />
          <skinnedMesh name="SmallCables005" geometry={nodes.SmallCables005.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables005.skeleton} />
          <skinnedMesh name="SmallCables006" geometry={nodes.SmallCables006.geometry} material={materials.Metal} skeleton={nodes.SmallCables006.skeleton} />
          <skinnedMesh name="SmallCables007" geometry={nodes.SmallCables007.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables007.skeleton} />
          <skinnedMesh name="SmallCables008" geometry={nodes.SmallCables008.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables008.skeleton} />
          <skinnedMesh name="SmallCables009" geometry={nodes.SmallCables009.geometry} material={materials.Metal} skeleton={nodes.SmallCables009.skeleton} />
          <skinnedMesh name="SmallCables010" geometry={nodes.SmallCables010.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables010.skeleton} />
          <skinnedMesh name="SmallCables011" geometry={nodes.SmallCables011.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables011.skeleton} />
          <skinnedMesh name="SmallCables012" geometry={nodes.SmallCables012.geometry} material={materials.Metal} skeleton={nodes.SmallCables012.skeleton} />
          <skinnedMesh name="SmallCables013" geometry={nodes.SmallCables013.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables013.skeleton} />
          <skinnedMesh name="SmallCables014" geometry={nodes.SmallCables014.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables014.skeleton} />
          <skinnedMesh name="SmallCables015" geometry={nodes.SmallCables015.geometry} material={materials.Metal} skeleton={nodes.SmallCables015.skeleton} />
          <skinnedMesh name="SmallCables016" geometry={nodes.SmallCables016.geometry} material={materials.BlackRubber} skeleton={nodes.SmallCables016.skeleton} />
          <skinnedMesh name="SmallCables017" geometry={nodes.SmallCables017.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables017.skeleton} />
          <skinnedMesh name="SmallCables018" geometry={nodes.SmallCables018.geometry} material={materials.Metal} skeleton={nodes.SmallCables018.skeleton} />
          <skinnedMesh name="SmallCables019" geometry={nodes.SmallCables019.geometry} material={materials.BeigeCables} skeleton={nodes.SmallCables019.skeleton} />
          <skinnedMesh name="SmallCables020" geometry={nodes.SmallCables020.geometry} material={materials.Metal} skeleton={nodes.SmallCables020.skeleton} />
          <skinnedMesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.BlackRubber} skeleton={nodes.Sphere.skeleton} />
          <skinnedMesh name="Torso_1" geometry={nodes.Torso_1.geometry} material={materials.BlackRubber} skeleton={nodes.Torso_1.skeleton} />
          <skinnedMesh name="UpperFace" geometry={nodes.UpperFace.geometry} material={materials.BlackRubber} skeleton={nodes.UpperFace.skeleton} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
    </group>
    </group>
  )
}

useGLTF.preload('/futura.glb')
