/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Hologram.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  useEffect(() => {
    actions['KeyAction.001'].play();
    actions['Action.002'].play();
    actions['Action.003'].play();
    actions['Action.004'].play();
    actions['Action.005'].play();
    actions['Action.006'].play();
    actions['Action.007'].play();
  })
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.010']} scale={6.13}>
          <mesh name="Icosphere002" geometry={nodes.Icosphere002.geometry} material={materials['Material.008']} position={[1, 0, 0]} scale={0.06} />
        </mesh>
        <mesh name="Circle643" geometry={nodes.Circle643.geometry} material={materials['Material.004']} scale={4.79} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.006']} rotation={[Math.PI, -0.13, Math.PI]} scale={0.97} />
        <mesh name="TERRE1" geometry={nodes.TERRE1.geometry} material={materials['Material.005']} scale={3.27} />
        <mesh name="Circle455" geometry={nodes.Circle455.geometry} material={materials['Material.007']} morphTargetDictionary={nodes.Circle455.morphTargetDictionary} morphTargetInfluences={nodes.Circle455.morphTargetInfluences} scale={0.18} />
      </group>
    </group>
  )
}

useGLTF.preload('/Hologram.glb')
