/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/planet.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['aereoAction.002'].play();
    actions['barcaAction.001'].play();
    actions['barca.002Action'].play();
    actions['barca.003Action'].play();
    actions['barca.004Action'].play();
    actions['barca.005Action'].play();
    actions['nuvolaAction'].play();
    actions['nuvola.001Action'].play();
    actions['nuvola.002Action'].play();
    actions['nuvola.003Action'].play();
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="mondo" geometry={nodes.mondo.geometry} material={materials['Material.003']} position={[0, 11.52, -0.02]} scale={1.54} />
        <mesh name="acqua" geometry={nodes.acqua.geometry} material={materials['Material.002']} position={[0, 11.52, -0.02]} scale={1.67} />
        <group name="albero" position={[1.16, 12.56, -0.91]} rotation={[-0.83, -0.32, -0.69]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero001" position={[1.29, 12.53, -0.72]} rotation={[-0.85, -0.3, -0.86]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero002" position={[1.31, 12.39, -0.89]} rotation={[-0.96, -0.16, -0.95]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero003" position={[1.17, 12.43, -1.03]} rotation={[-1.03, -0.09, -0.68]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero004" position={[1.4, 12.4, -0.69]} rotation={[-0.96, -0.16, -0.95]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero005" position={[1.26, 12.25, -1.05]} rotation={[-1.05, -0.06, -0.86]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero007" position={[1.13, 12.78, -0.19]} rotation={[-0.66, -0.54, -0.85]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero008" position={[1.37, 12.54, 0.03]} rotation={[-0.68, -0.47, -1.18]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero006" position={[1.4, 12.27, -0.84]} rotation={[-0.96, -0.16, -0.95]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero009" position={[0.67, 13.05, -0.35]} rotation={[-0.48, -0.7, -0.55]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero010" position={[-1.34, 12.52, 0]} rotation={[0.61, -0.48, 0.99]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero011" position={[0.34, 11.68, 1.73]} rotation={[1.5, 0.04, -0.16]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero012" position={[0.06, 12.12, 1.58]} rotation={[1.22, 0.09, -0.02]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero013" position={[0.55, 11.56, 1.7]} rotation={[1.41, 0.06, -0.31]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero014" position={[0.71, 11.69, 1.54]} rotation={[1.5, 0.03, -0.46]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero015" position={[0.34, 11.44, 1.74]} rotation={[1.66, 0, -0.16]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero016" position={[0.66, 11.38, 1.64]} rotation={[1.67, 0, -0.47]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero017" position={[1.54, 10.8, -0.03]} rotation={[1.92, -0.35, -1.44]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero018" position={[1.38, 10.54, 0.17]} rotation={[1.98, -0.55, -1.19]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero019" position={[1.36, 10.52, -0.21]} rotation={[2.01, -0.65, -1.45]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero020" position={[-0.58, 10.91, -1.6]} rotation={[-1.92, 0.1, 0.3]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero021" position={[-0.91, 10.78, -1.37]} rotation={[-2.03, 0.05, 0.56]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero022" position={[-0.7, 10.76, -1.48]} rotation={[-2.05, 0.04, 0.44]} scale={0.03}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero023" position={[-1.49, 11.23, 0.75]} rotation={[1.73, 0.03, 1.09]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero024" position={[-1.33, 10.7, 0.68]} rotation={[1.9, 0.34, 1.02]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero025" position={[-0.98, 10.58, 1.02]} rotation={[2.04, 0.44, 0.66]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero026" position={[-1.55, 12.22, -0.04]} rotation={[0.72, -0.25, 1.29]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero027" position={[0.73, 12.89, -0.72]} rotation={[-0.77, -0.55, -0.61]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero028" position={[-1.07, 10.74, -1.1]} rotation={[-2.17, -0.01, 0.68]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero029" position={[-0.09, 11.15, -1.68]} rotation={[-1.75, 0.07, 0]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="albero030" position={[0.96, 11.99, 1.31]} rotation={[1.24, 0.14, -0.57]} scale={0.04}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.005']} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.009']} />
        </group>
        <group name="casa" position={[-1.44, 12.42, -0.23]} rotation={[-0.01, -0.18, 0.93]} scale={0.51}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa001" position={[1.55, 12, -0.53]} rotation={[1.02, 0.46, -1.62]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa002" position={[1.54, 11.71, -0.71]} rotation={[1, 0.36, -1.9]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa003" position={[1.38, 11.8, -0.97]} rotation={[1.07, 0.51, -2]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa004" position={[0.66, 12.43, -1.3]} rotation={[1.57, 1.01, -2.43]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa005" position={[0.82, 12.17, -1.36]} rotation={[1.26, 0.81, -2.24]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa006" position={[0.73, 12.13, 1.4]} rotation={[1.35, 0.46, -0.49]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa007" position={[0.33, 12.11, 1.55]} rotation={[1.24, 0.49, -0.16]} scale={0.48}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa008" position={[-0.84, 10.49, -1.09]} rotation={[0.23, -0.67, 2.36]} scale={0.51}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa009" position={[-1.24, 10.94, 1]} rotation={[-0.57, 0.33, 2.22]} scale={0.51}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa010" position={[-1.13, 10.48, 0.73]} rotation={[-0.42, 0.21, 2.48]} scale={0.51}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="casa011" position={[-1.43, 12.41, 0.25]} rotation={[-0.38, 0.42, 1.05]} scale={0.51}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.008']} />
        </group>
        <group name="barca" position={[-0.61, 12.9, -0.68]} rotation={[-0.24, -0.66, 0.4]} scale={0.62}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.010']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.011']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.013']} />
        </group>
        <group name="barca002" position={[-0.38, 12.21, -1.46]} rotation={[1.55, -0.92, 2.65]} scale={0.62}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.010']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.011']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.013']} />
        </group>
        <group name="barca003" position={[-1.45, 11.81, -0.76]} rotation={[-0.29, -0.43, 1.36]} scale={0.62}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.010']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.011']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.013']} />
        </group>
        <group name="barca004" position={[-0.89, 12.25, 1.18]} rotation={[-1.34, 0.74, 2.27]} scale={0.62}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.010']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.011']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.013']} />
        </group>
        <group name="barca005" position={[-0.74, 10.05, -0.06]} rotation={[-0.2, -0.61, 2.64]} scale={0.62}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.010']} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.011']} />
          <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['Material.013']} />
        </group>
        <group name="aereo" position={[-0.02, 14.19, 0.17]} rotation={[0.13, 0.1, 0.38]} scale={0.77}>
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.014']} />
          <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['Material.015']} />
        </group>
        <mesh name="nuvola" geometry={nodes.nuvola.geometry} material={materials['Material.004']} position={[0.05, 14.06, -0.91]} rotation={[1.59, -0.06, 0.93]} scale={0.31} />
        <mesh name="nuvola002" geometry={nodes.nuvola002.geometry} material={materials['Material.004']} position={[-0.07, 12.51, -2.56]} rotation={[1.04, 0.06, -2.88]} scale={0.31} />
        <mesh name="nuvola001" geometry={nodes.nuvola001.geometry} material={materials['Material.007']} position={[0, 13.97, 1.62]} rotation={[0.64, -0.02, -0.12]} scale={0.23} />
        <mesh name="nuvola003" geometry={nodes.nuvola003.geometry} material={materials['Material.007']} position={[0.19, 9.68, -2.83]} rotation={[0.39, -0.67, 2.01]} scale={0.23} />
        <mesh name="Icosphere" geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[0.2, 13.11, 2.55]} rotation={[3.1, -0.14, -0.02]} scale={0.45} />
      </group>
    </group>
  )
}

useGLTF.preload('/planet.glb')
